# This workflow is triggered by github issue and creates a jira ticket in the respective configured account
#
name: Notify Jira
on:
  issues:
    types: [opened]

jobs:
  jira_job:
    runs-on: ubuntu-latest
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL}}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL}}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN}}
      - name: Jira Create issue
        id: create_jira_issue
        uses: atlassian/gajira-create@v3
        with:
          project: AST
          issuetype: Bug
          summary: '[GITHUB ISSUE] ${{github.event.issue.title}}'
          description: ${{github.event.issue.body}} see more at ${{github.event.issue.html_url}}
          fields: '{"team": 11, "cf[10014]": "${{ secrets.EPIC_LINK}}" }'

    - name: Add comment to GitHub issue
      uses: actions/github-script@v4.0.2
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Internal Jira issue: [${{ steps.create_jira_issue.outputs.issue }}](${{ inputs.JIRA_BASE_URL }}/browse/${{ steps.create_jira_issue.outputs.issue }})'
          })     
